name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-general:
    name: 'Test Package'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install .[dev]
      - name: Black Formatting
        run: |
          black --version
          black conda_store --diff
          black --check conda_store
      - name: Flake8 Formatting
        run: |
          flake8 --version
          flake8

  build-general:
    name: 'Build Docker Image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Infrastructure'
        uses: actions/checkout@master
      - name: Docker Build, Tag, Push Image
        env:
          IMAGE_NAME: quansight/conda-store
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .

  build-extension:
    name: 'Build JupyterLab Extension'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Frontend'
        uses: actions/checkout@v2
        with:
          ref: frontend
      - name: 'Setup conda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: extension/environment.yaml
          activate-environment: conda-store-extension
      - name: Bash
        shell: bash -l {0}
        run: |
          cd extension
          yarn
          pip install .
          jupyter labextension develop . --overwrite
          jlpm build
        
